#!/usr/bin/env bash



touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

x=1
while [ $x ]; do
      echo "To infinity and beyond"
      sleep 2

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript; exit' SIGQUIT


done
